// Code generated by hero.
// source: /Users/akshayjain/github/goTemplate/hero/userlist.html
// DO NOT EDIT!
package template

import "bytes"

func UserList(userList []string, buffer *bytes.Buffer) (int, error) {
	member := 0
	for _, user := range userList {
		if user != "" {
			member++
		}
	}
	return member, nil

}
